/* tslint:disable */
/* eslint-disable */
/**
 * Ampli - A strong typed wrapper for your Analytics
 *
 * This file is generated by Amplitude.
 * To update run 'ampli pull osmosis'
 *
 * Required dependencies: @amplitude/analytics-browser@^1.3.0
 * Tracking Plan Version: 5
 * Build: 1.0.0
 * Runtime: browser:javascript-ampli-v2
 *
 * [View Tracking Plan](https://data.amplitude.com/osmosis-zone/Osmosis%20%F0%9F%A7%AA/events/main/latest)
 *
 * [Full Setup Instructions](https://data.amplitude.com/osmosis-zone/Osmosis%20%F0%9F%A7%AA/implementation/osmosis)
 */

import * as amplitude from '@amplitude/analytics-browser';

/**
 * @typedef BaseEvent
 * @type {object}
 * @property {string} event_type
 * @property {Object.<string, *>} [event_properties]
 */

/**
 * @typedef Plan
 * @type {object}
 * @property {string} [branch]
 * @property {string} [source]
 * @property {string} [version]
 * @property {string} [versionId]
 */

/**
 * @typedef LoadClientOptions
 * @type {object}
 * @property {string} [apiKey]
 * @property {Object} [configuration]
 * @property {BrowserClient} [instance]
 */

/**
 * @typedef LoadOptions
 * @type {object}
 * @property {'development'|'production'} [environment]
 * @property {boolean} [disabled]
 * @property {LoadClientOptions} [client]
 */

/**
 * @typedef {Object} EventOptions
 * @type {object}
 */

/**
 * @typedef ApiKey
 * @type {object}
 * @property {string} development
 * @property {string} production
 */
export const ApiKey = {
  development: '',
  production: '4a125d3ac35ae9d27504e8e3e8319f9a'
};

/**
 * Default Amplitude configuration options. Contains tracking plan information.
 */
export const DefaultConfiguration = {
  plan: {
    version: '5',
    branch: 'main',
    source: 'osmosis',
    versionId: '97fde369-9bfa-48cd-89fe-055ba59b871b'
  },
  ...{
    ingestionMetadata: {
      sourceName: 'browser-javascript-ampli',
      sourceVersion: '2.0.0'
    }
  }
};

export class Identify {
  constructor(properties) {
    this.event_type = 'Identify';
    this.event_properties = properties;
  }
}

export class Group {
  constructor() {
    this.event_type = 'Group';
  }
}

/**
 * @typedef PromiseResult
 * @type {object}
 * @property {Promise|undefined} promise
 */

const getVoidPromiseResult = () => ({ promise: Promise.resolve() });

// prettier-ignore
export class Ampli {
  constructor() {
    /* @type {BrowserClient|undefined} */
    this.amplitude = undefined;
    this.disabled = false;
  }

  /**
   * @return {BrowserClient}
   */
  get client() {
    this.isInitializedAndEnabled();
    return this.amplitude;
  }

  /**
   * @return {boolean}
   */
  get isLoaded() {
    return this.amplitude != null;
  }

  /**
   * @private
   * @return {boolean}
   */
  isInitializedAndEnabled() {
    if (!this.isLoaded) {
      console.error('ERROR: Ampli is not yet initialized. Have you called ampli.load() on app start?');
      return false;
    }
    return !this.disabled;
  }

  /**
   * Initialize the Ampli SDK. Call once when your application starts.
   *
   * @param {LoadOptions} [options] Configuration options to initialize the Ampli SDK with.
   *
   * @return {PromiseResult}
   */
  load(options) {
    this.disabled = options?.disabled ?? false;

    if (this.isLoaded) {
      console.warn('WARNING: Ampli is already initialized. Ampli.load() should be called once at application startup.');
      return getVoidPromiseResult();
    }

    const env = options?.environment ?? 'development';
    const apiKey = options?.client?.apiKey ?? ApiKey[env];

    if (options?.client?.instance) {
      this.amplitude = options?.client?.instance;
    } else if (apiKey) {
      this.amplitude = amplitude.createInstance();
      return this.amplitude.init(apiKey, undefined, { ...DefaultConfiguration, ...options?.client?.configuration });
    } else {
      console.error("ERROR: ampli.load() requires 'environment', 'client.apiKey', or 'client.instance'");
    }

    return getVoidPromiseResult();
  }

  /**
   * Identify a user and set or update that user's properties.
   *
   * @param {string|undefined} userId The user's id.
   * @param {Object} [properties] The user's properties.
   * @param {*} [properties.bondedAssetsPrice] Property has no description in tracking plan.
   * @param {*} [properties.connectedWallet] Property has no description in tracking plan.
   * @param {*} [properties.fbclid] Property has no description in tracking plan.
   * @param {*} [properties.initial_fbclid] Property has no description in tracking plan.
   * @param {*} [properties.initial_gclid] Property has no description in tracking plan.
   * @param {*} [properties.initial_referrer] Property has no description in tracking plan.
   * @param {*} [properties.initial_referring_domain] Property has no description in tracking plan.
   * @param {*} [properties.initial_utm_campaign] Property has no description in tracking plan.
   * @param {*} [properties.initial_utm_content] Property has no description in tracking plan.
   * @param {*} [properties.initial_utm_medium] Property has no description in tracking plan.
   * @param {*} [properties.initial_utm_source] Property has no description in tracking plan.
   * @param {*} [properties.initial_utm_term] Property has no description in tracking plan.
   * @param {*} [properties.isWalletConnected] Property has no description in tracking plan.
   * @param {*} [properties.myPoolsCount] Property has no description in tracking plan.
   * @param {*} [properties.osmoBalance] Property has no description in tracking plan.
   * @param {*} [properties.referrer] Property has no description in tracking plan.
   * @param {*} [properties.referring_domain] Property has no description in tracking plan.
   * @param {*} [properties.stakedOsmoPrice] Property has no description in tracking plan.
   * @param {*} [properties.totalAssetsPrice] Property has no description in tracking plan.
   * @param {*} [properties.unbondedAssetsPrice] Property has no description in tracking plan.
   * @param {*} [properties.utm_campaign] Property has no description in tracking plan.
   * @param {*} [properties.utm_content] Property has no description in tracking plan.
   * @param {*} [properties.utm_medium] Property has no description in tracking plan.
   * @param {*} [properties.utm_source] Property has no description in tracking plan.
   * @param {*} [properties.utm_term] Property has no description in tracking plan.
   * @param {EventOptions} [options] Optional event options.
   *
   * @return {PromiseResult}
   */
  identify(userId, properties, options) {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    if (userId) {
      options = {...options, user_id: userId};
    }

    const ampIdentify = new amplitude.Identify();
    const eventProperties = properties;
    if (eventProperties != null) {
      for (const [key, value] of Object.entries(eventProperties)) {
        ampIdentify.set(key, value);
      }
    }
    return this.amplitude.identify(ampIdentify, options);
  }

  /**
   * Set Group for the current user
   *
   * @param {string} groupType The group type.
   * @param {string|string[]} groupName The group name.
   * @param {EventOptions} [options] Optional event options.
   *
   * @return {PromiseResult}
   */
  setGroup(groupType, groupName, options) {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    return this.amplitude.setGroup(groupType, groupName, options);
  }

  /**
   * Identify a group.
   *
   * @param {string} groupType The group type.
   * @param {string|string[]} groupName The group name.
   * @param {EventOptions} [options] Options for this groupIdentify call.
   *
   * @return {PromiseResult}
   */
  groupIdentify(groupType, groupName, options) {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    const amplitudeIdentify = new amplitude.Identify();
    return this.amplitude.groupIdentify(groupType, groupName, amplitudeIdentify, options);
  }

  /**
   * Track event
   *
   * @param {BaseEvent} event The event to track.
   * @param {EventOptions} [options] Optional event options.
   *
   * @return {PromiseResult}
   */
  track(event, options) {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    return this.amplitude.track(event, undefined, options);
  }

}

export const ampli = new Ampli();
